/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Company {
  export type EmployeeStruct = {
    pensionStartDate: PromiseOrValue<BigNumberish>;
    pensionDuration: PromiseOrValue<BigNumberish>;
    monthyAmount: PromiseOrValue<BigNumberish>;
    employeeJoiningDate: PromiseOrValue<BigNumberish>;
    employeeLeavingDate: PromiseOrValue<BigNumberish>;
    minimumServiceRequired: PromiseOrValue<BigNumberish>;
  };

  export type EmployeeStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    pensionStartDate: BigNumber;
    pensionDuration: BigNumber;
    monthyAmount: BigNumber;
    employeeJoiningDate: BigNumber;
    employeeLeavingDate: BigNumber;
    minimumServiceRequired: BigNumber;
  };
}

export interface CompanyInterface extends utils.Interface {
  functions: {
    "addEmployee(address,uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "addEmployees(address[],uint256[],uint256[],uint256[],uint256[],uint256[],uint256[],bool[])": FunctionFragment;
    "changeName(string)": FunctionFragment;
    "checkUpkeep(bytes)": FunctionFragment;
    "employeeAddresses(uint256)": FunctionFragment;
    "employees(address)": FunctionFragment;
    "getEmployee(address)": FunctionFragment;
    "getEmployees()": FunctionFragment;
    "initialize(address,string)": FunctionFragment;
    "lastPensionTimeStamp()": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateEmployee(address,uint256,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addEmployee"
      | "addEmployees"
      | "changeName"
      | "checkUpkeep"
      | "employeeAddresses"
      | "employees"
      | "getEmployee"
      | "getEmployees"
      | "initialize"
      | "lastPensionTimeStamp"
      | "name"
      | "owner"
      | "performUpkeep"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateEmployee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEmployee",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addEmployees",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<boolean>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "employeeAddresses",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "employees",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmployees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastPensionTimeStamp",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmployee",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "changeName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employeeAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastPensionTimeStamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmployee",
    data: BytesLike
  ): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Company extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CompanyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addEmployees(
      _employeeAddresses: PromiseOrValue<string>[],
      _pensionStartDates: PromiseOrValue<BigNumberish>[],
      _pensionDurations: PromiseOrValue<BigNumberish>[],
      _monthyAmounts: PromiseOrValue<BigNumberish>[],
      _employeeJoiningDates: PromiseOrValue<BigNumberish>[],
      _employeeLeavingDates: PromiseOrValue<BigNumberish>[],
      _minimumServiceRequireds: PromiseOrValue<BigNumberish>[],
      _employeeActives: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkUpkeep(
      checkData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

    employeeAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    employees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        pensionStartDate: BigNumber;
        pensionDuration: BigNumber;
        monthyAmount: BigNumber;
        employeeJoiningDate: BigNumber;
        employeeLeavingDate: BigNumber;
        minimumServiceRequired: BigNumber;
      }
    >;

    getEmployee(
      _employeeAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[Company.EmployeeStructOutput]>;

    getEmployees(
      overrides?: CallOverrides
    ): Promise<[Company.EmployeeStructOutput[]]>;

    initialize(
      _owner: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    lastPensionTimeStamp(overrides?: CallOverrides): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addEmployee(
    _employeeAddress: PromiseOrValue<string>,
    _pensionStartDate: PromiseOrValue<BigNumberish>,
    _pensionDuration: PromiseOrValue<BigNumberish>,
    _monthyAmount: PromiseOrValue<BigNumberish>,
    _employeeJoiningDate: PromiseOrValue<BigNumberish>,
    _employeeLeavingDate: PromiseOrValue<BigNumberish>,
    _minimumServiceRequired: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addEmployees(
    _employeeAddresses: PromiseOrValue<string>[],
    _pensionStartDates: PromiseOrValue<BigNumberish>[],
    _pensionDurations: PromiseOrValue<BigNumberish>[],
    _monthyAmounts: PromiseOrValue<BigNumberish>[],
    _employeeJoiningDates: PromiseOrValue<BigNumberish>[],
    _employeeLeavingDates: PromiseOrValue<BigNumberish>[],
    _minimumServiceRequireds: PromiseOrValue<BigNumberish>[],
    _employeeActives: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeName(
    _name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkUpkeep(
    checkData: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

  employeeAddresses(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  employees(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
      pensionStartDate: BigNumber;
      pensionDuration: BigNumber;
      monthyAmount: BigNumber;
      employeeJoiningDate: BigNumber;
      employeeLeavingDate: BigNumber;
      minimumServiceRequired: BigNumber;
    }
  >;

  getEmployee(
    _employeeAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Company.EmployeeStructOutput>;

  getEmployees(
    overrides?: CallOverrides
  ): Promise<Company.EmployeeStructOutput[]>;

  initialize(
    _owner: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  lastPensionTimeStamp(overrides?: CallOverrides): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  performUpkeep(
    performData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateEmployee(
    _employeeAddress: PromiseOrValue<string>,
    _pensionStartDate: PromiseOrValue<BigNumberish>,
    _pensionDuration: PromiseOrValue<BigNumberish>,
    _monthyAmount: PromiseOrValue<BigNumberish>,
    _employeeJoiningDate: PromiseOrValue<BigNumberish>,
    _employeeLeavingDate: PromiseOrValue<BigNumberish>,
    _minimumServiceRequired: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    addEmployees(
      _employeeAddresses: PromiseOrValue<string>[],
      _pensionStartDates: PromiseOrValue<BigNumberish>[],
      _pensionDurations: PromiseOrValue<BigNumberish>[],
      _monthyAmounts: PromiseOrValue<BigNumberish>[],
      _employeeJoiningDates: PromiseOrValue<BigNumberish>[],
      _employeeLeavingDates: PromiseOrValue<BigNumberish>[],
      _minimumServiceRequireds: PromiseOrValue<BigNumberish>[],
      _employeeActives: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    changeName(
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkUpkeep(
      checkData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { upkeepNeeded: boolean }>;

    employeeAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    employees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber] & {
        pensionStartDate: BigNumber;
        pensionDuration: BigNumber;
        monthyAmount: BigNumber;
        employeeJoiningDate: BigNumber;
        employeeLeavingDate: BigNumber;
        minimumServiceRequired: BigNumber;
      }
    >;

    getEmployee(
      _employeeAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Company.EmployeeStructOutput>;

    getEmployees(
      overrides?: CallOverrides
    ): Promise<Company.EmployeeStructOutput[]>;

    initialize(
      _owner: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    lastPensionTimeStamp(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addEmployees(
      _employeeAddresses: PromiseOrValue<string>[],
      _pensionStartDates: PromiseOrValue<BigNumberish>[],
      _pensionDurations: PromiseOrValue<BigNumberish>[],
      _monthyAmounts: PromiseOrValue<BigNumberish>[],
      _employeeJoiningDates: PromiseOrValue<BigNumberish>[],
      _employeeLeavingDates: PromiseOrValue<BigNumberish>[],
      _minimumServiceRequireds: PromiseOrValue<BigNumberish>[],
      _employeeActives: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkUpkeep(
      checkData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    employeeAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    employees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEmployee(
      _employeeAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEmployees(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _owner: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    lastPensionTimeStamp(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addEmployees(
      _employeeAddresses: PromiseOrValue<string>[],
      _pensionStartDates: PromiseOrValue<BigNumberish>[],
      _pensionDurations: PromiseOrValue<BigNumberish>[],
      _monthyAmounts: PromiseOrValue<BigNumberish>[],
      _employeeJoiningDates: PromiseOrValue<BigNumberish>[],
      _employeeLeavingDates: PromiseOrValue<BigNumberish>[],
      _minimumServiceRequireds: PromiseOrValue<BigNumberish>[],
      _employeeActives: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeName(
      _name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkUpkeep(
      checkData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    employeeAddresses(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    employees(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEmployee(
      _employeeAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEmployees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _owner: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    lastPensionTimeStamp(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateEmployee(
      _employeeAddress: PromiseOrValue<string>,
      _pensionStartDate: PromiseOrValue<BigNumberish>,
      _pensionDuration: PromiseOrValue<BigNumberish>,
      _monthyAmount: PromiseOrValue<BigNumberish>,
      _employeeJoiningDate: PromiseOrValue<BigNumberish>,
      _employeeLeavingDate: PromiseOrValue<BigNumberish>,
      _minimumServiceRequired: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
