/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as companyFactorySol from "./CompanyFactory.sol";
export type { companyFactorySol };
export type { Company } from "./Company";
export type { Lock } from "./Lock";
