/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Company } from "./Company";
export type { CompanyDAO } from "./CompanyDAO";
export type { CompanyFactory } from "./CompanyFactory";
export type { GovernanceToken } from "./GovernanceToken";
export type { Lock } from "./Lock";
export type { TimeLock } from "./TimeLock";
