/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Company__factory } from "./Company__factory";
export { CompanyDAO__factory } from "./CompanyDAO__factory";
export { CompanyFactory__factory } from "./CompanyFactory__factory";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
export { Lock__factory } from "./Lock__factory";
export { TimeLock__factory } from "./TimeLock__factory";
