/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as companyFactorySol from "./CompanyFactory.sol";
export { Company__factory } from "./Company__factory";
export { Lock__factory } from "./Lock__factory";
